const swaggerAutogen = require('swagger-autogen')()

swaggerAutogen('./swagger-output.json', ['./routes/endpoint.js']);

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Cliente",
            "description": "Endpoint de Clientes"
        },
        {
            "name": "Produto",
            "description": "Endpoint de Produtos"
        },
        {
            "name": "Plano",
            "description": "Endpoint de Planos"
        }
    ],
    definitions: {
    
        AddCliente: {
            "cpf": "45645645600",
            "nome": "José da Silva",
            "email": "jose@cliente.com",
            "dataDeNascimento": "2000-08-24 12:00:00.000",
            "genero": "Masculino",
            "rendaMensal": 2899.5
          },
        Response: {
            "id": "7e468f2e-11b6-41d1-b9f9-ca46dd9f5d8e"
        },
        AddProduto: {
            "nome": "Brasilprev Longo Prazo",
            "susep": "15414900840201817",
            "expiracaoDeVenda": "2024-01-01 12:00:00.000",
            "valorMinimoAporteInicial": 1000.0,
            "valorMinimoAporteExtra": 100.0,
            "idadeDeEntrada": 18,
            "idadeDeSaida": 60,
            "carenciaInicialDeResgate": 60,
            "carenciaEntreResgates": 30
        },
        AddPlano: {
            "idCliente": "18dfeb91-459a-4bc7-9cdd-d93b41f7bf62",
            "idProduto": "30f6b23f-c93d-4cf9-8916-bcdb9fac83df",
            "aporte": 2000.00,
            "dataDaContratacao": "2022-04-05 12:00:00.000",
            "idadeDeAposentadoria": 60
        },
        AportePlano: {
            "idCliente": "77a819c5-bb2f-4ade-84a2-a81dfc67428b",
            "idPlano": "24fb6c42-6234-402e-ac84-2306d8c16137",
            "valorAporte": 100.00
        },
        ResgatePlano: {
            "idPlano": "98add7e5-1475-4af0-8478-8a94965e7000",
            "valorResgate": 1000.00
        }	
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routes/endpoint.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           
})